/*
 * Postman Delivery Management
 *
 * This is Postman Delivery Management API with Swagger documentation
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type HandlerOfficesResponse struct {
	Accountofficeid int32 `json:"accountofficeid,omitempty"`
	Deliveryofficeflag bool `json:"deliveryofficeflag,omitempty"`
	Officeid int32 `json:"officeid,omitempty"`
	Officename string `json:"officename,omitempty"`
	Officestatusid int32 `json:"officestatusid,omitempty"`
	Officetypecode string `json:"officetypecode,omitempty"`
	Paocode string `json:"paocode,omitempty"`
	Pincode string `json:"pincode,omitempty"`
	Reportingofficeid int32 `json:"reportingofficeid,omitempty"`
}
