/*
 * Postman Delivery Management
 *
 * This is Postman Delivery Management API with Swagger documentation
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ResponseListReportsEmOsPaidResponse struct {
	EmoPaidDetails []DomainEMoTransactions `json:"emo_paid_details,omitempty"`
}
