/*
 * Master Data Management API
 *
 * A comprehensive API suite for managing various aspects of the postal system, including office management, product management, tariffs (domestic and international), product country mapping, local pin codes, country details, and currency exchange rates. Additionally, the API supports insurance quote generation for PLI/RPLI, and interest rate calculations for savings schemes such as SB, SSA, PPF, MIS, TD, NSC/KVP, SCSS, and MSS.
 *
 * API version: 1.0
 * Contact: support_cept@indiapost.gov.in
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ResponseGetEmoTariffResponse struct {
	EmoCommission float32 `json:"emo_commission,omitempty"`
	EmoPrice float32 `json:"emo_price,omitempty"`
	EmoTotalPrice float32 `json:"emo_total_price,omitempty"`
	ProductCode string `json:"product_code,omitempty"`
}
