/*
 * Postman Delivery Management
 *
 * This is Postman Delivery Management API with Swagger documentation
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ResponseListEmoReturnsResponse struct {
	EmoNumber string `json:"emo_number,omitempty"`
	EmoValue float32 `json:"emo_value,omitempty"`
	Remarks string `json:"remarks,omitempty"`
}
