/*
 * Master Data Management
 *
 * This is Master Data Management API with Swagger documentation
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type DomainRpliQuoteGenerationRequest struct {
	AgeOnNextBirthday float32 `json:"age_on_next_birthday"`
	ChildAge float32 `json:"child_age,omitempty"`
	IsNewPolicy int32 `json:"is_new_policy"`
	// Standard-1 Non-Standard-2
	IsNonStdAge int32 `json:"is_non_std_age"`
	// Monthly-1 Quarterly-2 HalfYearly-3 Yearly-4
	Periodicity int32 `json:"periodicity"`
	SumAssured float32 `json:"sum_assured"`
	SumAssuredChildPolicy float32 `json:"sum_assured_child_policy,omitempty"`
}
