/*
 * Postman Delivery Management
 *
 * This is Postman Delivery Management API with Swagger documentation
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type HandlerRemarksId struct {
	Number string `json:"number,omitempty"`
	RemarksId string `json:"remarks_id,omitempty"`
}
