/*
 * Postman Delivery Management
 *
 * This is Postman Delivery Management API with Swagger documentation
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type HandlerCreateArticlesBulkWindowDeliveryRequest struct {
	ArticleArray []string `json:"article_array"`
	IdProofDocumentNumber string `json:"id_proof_document_number"`
	IdProofDocumentType string `json:"id_proof_document_type"`
	IsDigitalPayment bool `json:"is_digital_payment,omitempty"`
	OfficeId int32 `json:"office_id"`
	WindowDeliveredEmployeeId string `json:"window_delivered_employee_id"`
	WindowReceiverMobileNumber int32 `json:"window_receiver_mobile_number,omitempty"`
	WindowReceiverName string `json:"window_receiver_name"`
}
