/*
 * Master Data Management
 *
 * This is Master Data Management API with Swagger documentation
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type HandlerMergeOfficeRequestSourceOfficeDetails struct {
	AdminFlag bool `json:"admin_flag,omitempty"`
	DeliveryOfficeFlag bool `json:"delivery_office_flag,omitempty"`
	ModifiedBy string `json:"modified_by,omitempty"`
	OfficeId int32 `json:"office_id,omitempty"`
	OfficeStatus string `json:"office_status,omitempty"`
	OrderMemoNumber string `json:"order_memo_number,omitempty"`
	Remarks string `json:"remarks,omitempty"`
	SupportedDocumentPath string `json:"supported_document_path,omitempty"`
	// Change the type if necessary
	ValidTo string `json:"valid_to,omitempty"`
}
