/*
 * Postman Delivery Management
 *
 * This is Postman Delivery Management API with Swagger documentation
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ResponseListSubmitAccountsResponse struct {
	ArticleCount int32 `json:"article_count,omitempty"`
	EmoCount int32 `json:"emo_count,omitempty"`
	Totalamount float32 `json:"totalamount,omitempty"`
}
