/*
 * Postman Delivery Management
 *
 * This is Postman Delivery Management API with Swagger documentation
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ResponseListArticleReturnsResponse struct {
	ArticleNumber string `json:"article_number,omitempty"`
	Remarks string `json:"remarks,omitempty"`
	TotalAmountToBeCollected float32 `json:"total_amount_to_be_collected,omitempty"`
}
