/*
 * Master Data Management
 *
 * This is Master Data Management API with Swagger documentation
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type DomainOfficeTypeMaster struct {
	AdminFlag bool `json:"admin_flag,omitempty"`
	ChildOfficeTypeCode string `json:"child_office_type_code,omitempty"`
	OfficeTypeCode string `json:"office_type_code,omitempty"`
	OfficeTypeId int32 `json:"office_type_id,omitempty"`
	OfficeTypeName string `json:"office_type_name,omitempty"`
	ParentOfficeTypeCode string `json:"parent_office_type_code,omitempty"`
}
