/*
 * Postman Delivery Management
 *
 * This is Postman Delivery Management API with Swagger documentation
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ResponseFetchEmoRemarksResponse struct {
	ActionCode int32 `json:"action_code,omitempty"`
	ActionToBeTaken string `json:"action_to_be_taken,omitempty"`
	BatchName string `json:"batch_name,omitempty"`
	BeatName string `json:"beat_name,omitempty"`
	CreatedBy string `json:"created_by,omitempty"`
	EmoNumber string `json:"emo_number,omitempty"`
	InvoicedDate string `json:"invoiced_date,omitempty"`
	PersonnelId int32 `json:"personnel_id,omitempty"`
	PersonnelName string `json:"personnel_name,omitempty"`
	Remarks string `json:"remarks,omitempty"`
	RemarksId string `json:"remarks_id,omitempty"`
	SupervisorApprovalFlag bool `json:"supervisor_approval_flag,omitempty"`
	SupervisorApprovalType int32 `json:"supervisor_approval_type,omitempty"`
}
