/*
 * Master Data Management
 *
 * This is Master Data Management API with Swagger documentation
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type HandlerLocalPinRequest struct {
	LocalPin []DomainLocalPinDetail `json:"local_pin,omitempty"`
}
