/*
 * Postman Delivery Management
 *
 * This is Postman Delivery Management API with Swagger documentation
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type HandlerCreateArticleReturnsBulkSupervisorApprovalOfBoReturnsRequest struct {
	BatchName string `json:"batch_name"`
	BeatName string `json:"beat_name"`
	OfficeId int32 `json:"office_id"`
}
