/*
 * Master Data Management
 *
 * This is Master Data Management API with Swagger documentation
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type DomainDivision struct {
	CircleId int32 `json:"circle_id,omitempty"`
	DivisionId int32 `json:"division_id,omitempty"`
	DivisionName string `json:"division_name,omitempty"`
	RegionId int32 `json:"region_id,omitempty"`
}
