/*
 * Master Data Management API
 *
 * A comprehensive API suite for managing various aspects of the postal system, including office management, product management, tariffs (domestic and international), product country mapping, local pin codes, country details, and currency exchange rates. Additionally, the API supports insurance quote generation for PLI/RPLI, and interest rate calculations for savings schemes such as SB, SSA, PPF, MIS, TD, NSC/KVP, SCSS, and MSS.
 *
 * API version: 1.0
 * Contact: support_cept@indiapost.gov.in
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ResponseGetFgnBlindLiteratureTariffResponse struct {
	BasePrice float32 `json:"basePrice,omitempty"`
	Cgst float32 `json:"cgst,omitempty"`
	ChargeableWeight float32 `json:"chargeableWeight,omitempty"`
	CountryCode string `json:"countryCode,omitempty"`
	FgnBlindLiteratureTariff *DomainFgnBlindLiteraturePrice `json:"fgnBlindLiteratureTariff,omitempty"`
	Gst float32 `json:"gst,omitempty"`
	ModeOfTransmission []string `json:"modeOfTransmission,omitempty"`
	ProductCode string `json:"productCode,omitempty"`
	Sgst float32 `json:"sgst,omitempty"`
	TotalPriceWithoutTax float32 `json:"totalPriceWithoutTax,omitempty"`
	TotalWithTax float32 `json:"totalWithTax,omitempty"`
	VasDetails []DomainGetVasDetails `json:"vasDetails,omitempty"`
}
