/*
 * Master Data Management
 *
 * This is Master Data Management API with Swagger documentation
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type HandlerCreateEstablishmentRegisterRequest struct {
	ErName string `json:"er_name,omitempty"`
	OfficeId int32 `json:"office_id"`
	OfficeName string `json:"office_name"`
	// OfficeTypeCode          string `json:\"office_type_code\" validate:\"required\"`
	OfficeTypeName string `json:"office_type_name,omitempty"`
	OrdermemoNo string `json:"ordermemo_no"`
	Remarks string `json:"remarks,omitempty"`
	SupportDocPath string `json:"support_doc_path"`
	TotalSanctionedStrength int32 `json:"total_sanctioned_strength"`
}
