/*
 * Postman Delivery Management
 *
 * This is Postman Delivery Management API with Swagger documentation
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ResponseListReportsUnregisteredArticlesResponse struct {
	AckStatus int32 `json:"ack_status,omitempty"`
	BatchName string `json:"batch_name,omitempty"`
	BeatName string `json:"beat_name,omitempty"`
	CreatedBy string `json:"created_by,omitempty"`
	CreatedDate string `json:"created_date,omitempty"`
	IsSubmitAccount bool `json:"is_submit_account,omitempty"`
	NoOfArticle int32 `json:"no_of_article,omitempty"`
	NoOfArticleDel int32 `json:"no_of_article_del,omitempty"`
	OfficeId int32 `json:"office_id,omitempty"`
	OfficeName string `json:"office_name,omitempty"`
	PersonnelId int32 `json:"personnel_id,omitempty"`
	PersonnelName string `json:"personnel_name,omitempty"`
	PostageDue float32 `json:"postage_due,omitempty"`
	PostageDueCollected float32 `json:"postage_due_collected,omitempty"`
	UnregArticleId int32 `json:"unreg_article_id,omitempty"`
}
