/*
 * Postman Delivery Management
 *
 * This is Postman Delivery Management API with Swagger documentation
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type HandlerCreatePaymentsRequest struct {
	Amount string `json:"amount,omitempty"`
	ApplicationId int32 `json:"application_id,omitempty"`
	Authtype string `json:"authtype,omitempty"`
	Channel string `json:"channel,omitempty"`
	Counter string `json:"counter,omitempty"`
	EmployeeId string `json:"employee_id,omitempty"`
	Gstbreakup string `json:"gstbreakup,omitempty"`
	OfficeId string `json:"office_id,omitempty"`
	Pincode string `json:"pincode,omitempty"`
	ProductId string `json:"product_id,omitempty"`
	TransactionId string `json:"transaction_id,omitempty"`
	TransactionNote string `json:"transaction_note,omitempty"`
}
