/*
 * Postman Delivery Management
 *
 * This is Postman Delivery Management API with Swagger documentation
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type HandlerCreateEmoReturnsBulkMissentRedirectionWithoutInvoicingRequest struct {
	CurrentUser string `json:"current_user"`
	EmoArray []string `json:"emo_array"`
	OfficeId int32 `json:"office_id"`
	RedirectedAddress1 string `json:"redirected_address1,omitempty"`
	RedirectedAddress2 string `json:"redirected_address2,omitempty"`
	RedirectedAddress3 string `json:"redirected_address3,omitempty"`
	RedirectedCity string `json:"redirected_city,omitempty"`
	RedirectedOfficeId int32 `json:"redirected_office_id"`
	RedirectedOfficeName string `json:"redirected_office_name"`
	RedirectedPincode int32 `json:"redirected_pincode"`
	RedirectedState string `json:"redirected_state,omitempty"`
}
