/*
 * Postman Delivery Management
 *
 * This is Postman Delivery Management API with Swagger documentation
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type HandlerCreateArticleReturnsBulkSupervisorApprovalForMissentRequest struct {
	ArticleArray []string `json:"article_array"`
	CurrentUser string `json:"current_user"`
	OfficeId int32 `json:"office_id"`
}
