/*
 * Postman Delivery Management
 *
 * This is Postman Delivery Management API with Swagger documentation
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type HandlerBulkAddresseeDataResponse struct {
	// New Addition
	Batchname string `json:"batchname,omitempty"`
	// New Addition
	Beatname string `json:"beatname,omitempty"`
	Bulkaddresseeaddress1 string `json:"bulkaddresseeaddress1,omitempty"`
	Bulkaddresseeaddress2 string `json:"bulkaddresseeaddress2,omitempty"`
	Bulkaddresseeaddress3 string `json:"bulkaddresseeaddress3,omitempty"`
	Bulkaddresseecity string `json:"bulkaddresseecity,omitempty"`
	Bulkaddresseeid string `json:"bulkaddresseeid,omitempty"`
	Bulkaddresseename string `json:"bulkaddresseename,omitempty"`
	Bulkaddresseestate string `json:"bulkaddresseestate,omitempty"`
	// New Addition
	Createdby string `json:"createdby,omitempty"`
	// New Addition
	Createddate string `json:"createddate,omitempty"`
	Facilityid int32 `json:"facilityid,omitempty"`
	Id int32 `json:"id,omitempty"`
}
