/*
 * Postman Delivery Management
 *
 * This is Postman Delivery Management API with Swagger documentation
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type HandlerCreateEmoReturnsBulkAlterReturnsRequest struct {
	BeatName string `json:"beat_name,omitempty"`
	BoId int32 `json:"bo_id,omitempty"`
	BoName string `json:"bo_name,omitempty"`
	CurrentUser string `json:"current_user"`
	DestinationOfficeId int32 `json:"destination_office_id,omitempty"`
	DestinationOfficeName string `json:"destination_office_name,omitempty"`
	EmoRemarks *HandlerEmoRemarksId `json:"emo_remarks"`
	ModifiedActionCode int32 `json:"modified_action_code"`
	ModifiedActionToBeTaken string `json:"modified_action_to_be_taken"`
	ModifiedRemarks string `json:"modified_remarks"`
	ModifiedRemarksId string `json:"modified_remarks_id"`
	NoOfDaysOnHold int32 `json:"no_of_days_on_hold,omitempty"`
	OfficeId int32 `json:"office_id"`
	ReceiverAddress1 string `json:"receiver_address1,omitempty"`
	ReceiverAddress2 string `json:"receiver_address2,omitempty"`
	ReceiverAddress3 string `json:"receiver_address3,omitempty"`
	ReceiverCity string `json:"receiver_city,omitempty"`
	ReceiverMobileNo int32 `json:"receiver_mobile_no,omitempty"`
	ReceiverName string `json:"receiver_name,omitempty"`
	ReceiverPincode int32 `json:"receiver_pincode,omitempty"`
	ReceiverState string `json:"receiver_state,omitempty"`
	RedirectedAddress1 string `json:"redirected_address1,omitempty"`
	RedirectedAddress2 string `json:"redirected_address2,omitempty"`
	RedirectedAddress3 string `json:"redirected_address3,omitempty"`
	RedirectedBoId int32 `json:"redirected_bo_id,omitempty"`
	RedirectedBoName string `json:"redirected_bo_name,omitempty"`
	RedirectedCity string `json:"redirected_city,omitempty"`
	RedirectedOfficeId int32 `json:"redirected_office_id,omitempty"`
	RedirectedOfficeName string `json:"redirected_office_name,omitempty"`
	RedirectedPincode int32 `json:"redirected_pincode,omitempty"`
	RedirectedState string `json:"redirected_state,omitempty"`
}
