/*
 * Master Data Management API
 *
 * A comprehensive API suite for managing various aspects of the postal system, including office management, product management, tariffs (domestic and international), product country mapping, local pin codes, country details, and currency exchange rates. Additionally, the API supports insurance quote generation for PLI/RPLI, and interest rate calculations for savings schemes such as SB, SSA, PPF, MIS, TD, NSC/KVP, SCSS, and MSS.
 *
 * API version: 1.0
 * Contact: support_cept@indiapost.gov.in
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ResponseCreateCountryResponse struct {
	AirMailSurchargeIndicatorFlag bool `json:"air_mail_surcharge_indicator_flag,omitempty"`
	AmsApplicableCharge int32 `json:"ams_applicable_charge,omitempty"`
	CountryCode string `json:"country_code,omitempty"`
	CountryId int32 `json:"country_id,omitempty"`
	CountryName string `json:"country_name,omitempty"`
	CreatedBy string `json:"created_by,omitempty"`
	CreatedDate string `json:"created_date,omitempty"`
	DelFlag bool `json:"del_flag,omitempty"`
	SalApplicableCharge float32 `json:"sal_applicable_charge,omitempty"`
	Status string `json:"status,omitempty"`
	SurfaceAirLiftedIndicator bool `json:"surface_air_lifted_indicator,omitempty"`
}
