/*
 * Postman Delivery Management
 *
 * This is Postman Delivery Management API with Swagger documentation
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ResponseFetchOfficeShiftsStatusResponse struct {
	Createdby string `json:"createdby,omitempty"`
	Createddate string `json:"createddate,omitempty"`
	Isshiftbegin bool `json:"isshiftbegin,omitempty"`
	Isshiftend bool `json:"isshiftend,omitempty"`
	Officeid int32 `json:"officeid,omitempty"`
	Officename string `json:"officename,omitempty"`
	Reasonfordelayshiftend string `json:"reasonfordelayshiftend,omitempty"`
	Shiftenddate string `json:"shiftenddate,omitempty"`
	Shiftid int32 `json:"shiftid,omitempty"`
	// Assuming you want to represent date as a string
	Shiftstartdate string `json:"shiftstartdate,omitempty"`
}
