/*
 * Master Data Management API
 *
 * A comprehensive API suite for managing various aspects of the postal system, including office management, product management, tariffs (domestic and international), product country mapping, local pin codes, country details, and currency exchange rates. Additionally, the API supports insurance quote generation for PLI/RPLI, and interest rate calculations for savings schemes such as SB, SSA, PPF, MIS, TD, NSC/KVP, SCSS, and MSS.
 *
 * API version: 1.0
 * Contact: support_cept@indiapost.gov.in
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ResponseUpdateOfficeDetails struct {
	AdminFlag bool `json:"admin_flag,omitempty"`
	DeliveryOfficeFlag bool `json:"delivery_office_flag,omitempty"`
	ModifiedBy string `json:"modified_by,omitempty"`
	OfficeId int32 `json:"office_id,omitempty"`
	OfficeStatus string `json:"office_status,omitempty"`
	OrderMemoNumber string `json:"order_memo_number,omitempty"`
	Remarks string `json:"remarks,omitempty"`
	SupportedDocumentPath string `json:"supported_document_path,omitempty"`
	ValidTo string `json:"valid_to,omitempty"`
}
