/*
 * Postman Delivery Management
 *
 * This is Postman Delivery Management API with Swagger documentation
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ResponseCreateArticleReturnsBulkSupervisorApprovalApiResponse struct {
	Data string `json:"data,omitempty"`
	Message string `json:"message,omitempty"`
	StatusCode int32 `json:"status_code,omitempty"`
}
