/*
 * Postman Delivery Management
 *
 * This is Postman Delivery Management API with Swagger documentation
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ResponseListReportsEmOsAbstractResponse struct {
	EmoDeliveredThroughWindow []DomainEMoTransactions `json:"emo_delivered_through_window,omitempty"`
	EmoDeliveredbypostman []DomainEMoTransactions `json:"emo_deliveredbypostman,omitempty"`
	EmoDepositedAbstract []DomainEMoTransactions `json:"emo_deposited_abstract,omitempty"`
	EmoDepositedtoday []DomainEMoTransactions `json:"emo_depositedtoday,omitempty"`
	EmoIssuedtobo []DomainEMoTransactions `json:"emo_issuedtobo,omitempty"`
	EmoIssuedtopostman []DomainEMoTransactions `json:"emo_issuedtopostman,omitempty"`
	EmoPaidatbo []DomainEMoTransactions `json:"emo_paidatbo,omitempty"`
	EmoPendingforprintingtilldate []DomainEMoTransactions `json:"emo_pendingforprintingtilldate,omitempty"`
	EmoPrintedtoday []DomainEMoTransactions `json:"emo_printedtoday,omitempty"`
	EmoReceivedtoday []DomainEMoTransactions `json:"emo_receivedtoday,omitempty"`
	EmoRedirected []DomainEMoTransactions `json:"emo_redirected,omitempty"`
	EmoReturnedTosender []DomainEMoTransactions `json:"emo_returned_tosender,omitempty"`
}
