/*
 * Master Data Management API
 *
 * A comprehensive API suite for managing various aspects of the postal system, including office management, product management, tariffs (domestic and international), product country mapping, local pin codes, country details, and currency exchange rates. Additionally, the API supports insurance quote generation for PLI/RPLI, and interest rate calculations for savings schemes such as SB, SSA, PPF, MIS, TD, NSC/KVP, SCSS, and MSS.
 *
 * API version: 1.0
 * Contact: support_cept@indiapost.gov.in
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type HandlerCreateIntProductCountryMappingRequest struct {
	// Country code (required)
	CountryCode string `json:"country_code"`
	// Creator's email (required)
	CreatedBy string `json:"created_by"`
	// Dimension length, breadth, height (optional)
	DimensionLengthBreadthHeight float32 `json:"dimension_length_breadth_height,omitempty"`
	// Insurance higher limit (optional)
	InsHigherLimit float32 `json:"ins_higher_limit,omitempty"`
	// Insurance lower limit (optional)
	InsLowerLimit float32 `json:"ins_lower_limit,omitempty"`
	// Length of roll form in cms (optional)
	LengthOfRollFormInCms float32 `json:"length_of_roll_form_in_cms,omitempty"`
	// Length plus two times diameter in roll (optional)
	LengthPlus2TimesDiameterInRoll float32 `json:"length_plus_2_times_diameter_in_roll,omitempty"`
	// Maximum breadth in non-roll form in cms (optional)
	MaxBreadthOfNonRollFormInCms float32 `json:"max_breadth_of_non_roll_form_in_cms,omitempty"`
	// Maximum height in non-roll form in cms (optional)
	MaxHeightOfNonRollFormInCms float32 `json:"max_height_of_non_roll_form_in_cms,omitempty"`
	// Maximum length in non-roll form in cms (optional)
	MaxLengthOfNonRollFormInCms float32 `json:"max_length_of_non_roll_form_in_cms,omitempty"`
	// Maximum weight in grams (optional)
	MaxWeightGms float32 `json:"max_weight_gms,omitempty"`
	// Minimum weight in grams (optional)
	MinWeightGms float32 `json:"min_weight_gms,omitempty"`
	// Minimum breadth in non-roll form (optional)
	MinimumBreathInNonRoll float32 `json:"minimum_breath_in_non_roll,omitempty"`
	// Minimum height in non-roll form (optional)
	MinimumHeightInNonRoll float32 `json:"minimum_height_in_non_roll,omitempty"`
	// Minimum length in non-roll form (optional)
	MinimumLengthInNonRoll float32 `json:"minimum_length_in_non_roll,omitempty"`
	// Minimum length in roll (optional)
	MinimumLengthInRoll float32 `json:"minimum_length_in_roll,omitempty"`
	// Mode of transmission (required)
	ModeOfTransmission string `json:"mode_of_transmission"`
	// Product code (required)
	ProductCode string `json:"product_code"`
	// Status of mapping (required)
	Status string `json:"status"`
}
