/*
 * Postman Delivery Management
 *
 * This is Postman Delivery Management API with Swagger documentation
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ResponseListSubmitAccountsAmountCollectedResponse struct {
	DigitalTxnAmount float32 `json:"digital_txn_amount,omitempty"`
	DigitalTxnCount int32 `json:"digital_txn_count,omitempty"`
	NonDigitalTxnAmount float32 `json:"non_digital_txn_amount,omitempty"`
	NonDigitalTxnCount int32 `json:"non_digital_txn_count,omitempty"`
	TransactionType string `json:"transaction_type,omitempty"`
}
