/*
 * Master Data Management
 *
 * This is Master Data Management API with Swagger documentation
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type HandlerAddCountryRequest struct {
	ContinentCd string `json:"ContinentCd"`
	ContinentName string `json:"ContinentName"`
	CountryISDCode string `json:"CountryISDCode"`
	AddedBy string `json:"added_by"`
	AirMailSurchargeIndicatorFlag bool `json:"air_mail_surcharge_indicator_flag"`
	AmsApplicableCharge int32 `json:"ams_applicable_charge,omitempty"`
	CountryCode string `json:"country_code"`
	CountryName string `json:"country_name"`
	SalApplicableCharge float32 `json:"sal_applicable_charge"`
	Status string `json:"status"`
	SurfaceAirLiftedIndicator bool `json:"surface_air_lifted_indicator"`
}
