/*
 * Postman Delivery Management
 *
 * This is Postman Delivery Management API with Swagger documentation
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ResponseFetchArticlesCountForAbstractResponse struct {
	ArticleReceivedToday int32 `json:"article_received_today,omitempty"`
	ArticlesDeliveredByPostman int32 `json:"articles_delivered_by_postman,omitempty"`
	ArticlesDeliveredThroughWindow int32 `json:"articles_delivered_through_window,omitempty"`
	ArticlesIssuedToBo int32 `json:"articles_issued_to_bo,omitempty"`
	ArticlesIssuedToPostman int32 `json:"articles_issued_to_postman,omitempty"`
	ArticlesRedirected int32 `json:"articles_redirected,omitempty"`
	ArticlesReturnedToSender int32 `json:"articles_returned_to_sender,omitempty"`
	ArticlesUnprocessed int32 `json:"articles_unprocessed,omitempty"`
	DepositedArticles int32 `json:"deposited_articles,omitempty"`
}
