/*
 * Postman Delivery Management
 *
 * This is Postman Delivery Management API with Swagger documentation
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ConstsShiftType string

// List of consts.ShiftType
const (
	BEGIN ConstsShiftType = "begin"
	END ConstsShiftType = "end"
	FORCE_END ConstsShiftType = "force-end"
)
