/*
 * Postman Delivery Management
 *
 * This is Postman Delivery Management API with Swagger documentation
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type HandlerCreateArticlesBulkRemoveMakerCheckerRequest struct {
	ArticleArray []HandlerRemarksId `json:"article_array,omitempty"`
	BatchName string `json:"batch_name,omitempty"`
	BeatName string `json:"beat_name,omitempty"`
	CreatedAt string `json:"created_at,omitempty"`
	CreatedBy string `json:"created_by,omitempty"`
	CurrentUser string `json:"current_user,omitempty"`
	EmoArray []HandlerRemarksId `json:"emo_array,omitempty"`
	OfficeId int32 `json:"office_id,omitempty"`
	PersonnelId int32 `json:"personnel_id,omitempty"`
	Pincode int32 `json:"pincode,omitempty"`
	RequestUserId int32 `json:"request_user_id,omitempty"`
	TotalAmount float32 `json:"total_amount,omitempty"`
}
