/*
 * Master Data Management
 *
 * This is Master Data Management API with Swagger documentation
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type DomainCreateAccountCodeDetails struct {
	CreatedBy string `json:"created_by,omitempty"`
	GlCode int32 `json:"gl_code,omitempty"`
	GlId int32 `json:"gl_id,omitempty"`
	GlName string `json:"gl_name,omitempty"`
	Hoa string `json:"hoa,omitempty"`
	HoaName string `json:"hoa_name,omitempty"`
	OrderNumber string `json:"order_number,omitempty"`
	PaymentFlag bool `json:"payment_flag,omitempty"`
	ProductCode string `json:"product_code,omitempty"`
	ProductId int32 `json:"product_id,omitempty"`
	ReceiptFlag bool `json:"receipt_flag,omitempty"`
	Remarks string `json:"remarks,omitempty"`
	SupportedDocPath string `json:"supported_doc_path,omitempty"`
}
