/*
 * Postman Delivery Management
 *
 * This is Postman Delivery Management API with Swagger documentation
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type HandlerOfficeDataResponse struct {
	Bofacilityid int32 `json:"bofacilityid,omitempty"`
	Branchofficename string `json:"branchofficename,omitempty"`
}
