/*
 * Master Data Management API
 *
 * A comprehensive API suite for managing various aspects of the postal system, including office management, product management, tariffs (domestic and international), product country mapping, local pin codes, country details, and currency exchange rates. Additionally, the API supports insurance quote generation for PLI/RPLI, and interest rate calculations for savings schemes such as SB, SSA, PPF, MIS, TD, NSC/KVP, SCSS, and MSS.
 *
 * API version: 1.0
 * Contact: support_cept@indiapost.gov.in
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type HandlerCreateOfficeRequest struct {
	AccountingOfficeId int32 `json:"accounting_office_id,omitempty"`
	AdminFlag bool `json:"admin_flag,omitempty"`
	AdminOfficeId int32 `json:"admin_office_id,omitempty"`
	ApprovalStatus string `json:"approval_status,omitempty"`
	ApprovedBy string `json:"approved_by,omitempty"`
	AtmId string `json:"atm_id,omitempty"`
	BoId int32 `json:"bo_id,omitempty"`
	BoName string `json:"bo_name,omitempty"`
	// Optional office name fields
	CircleName string `json:"circle_name,omitempty"`
	// Optional office ID fields
	CircleOfficeId int32 `json:"circle_office_id,omitempty"`
	CityName string `json:"city_name"`
	ClosedDate string `json:"closed_date,omitempty"`
	ContactNumber string `json:"contact_number"`
	CreatedBy string `json:"created_by,omitempty"`
	CsiFacilityId string `json:"csi_facility_id,omitempty"`
	Dac string `json:"dac,omitempty"`
	DdoCode string `json:"ddo_code,omitempty"`
	DeletedFlag bool `json:"deleted_flag,omitempty"`
	DeliveryOfficeFlag bool `json:"delivery_office_flag,omitempty"`
	DivisionName string `json:"division_name,omitempty"`
	DivisionOfficeId int32 `json:"division_office_id,omitempty"`
	EmailId string `json:"email_id"`
	GstnCode string `json:"gstn_code,omitempty"`
	HoId int32 `json:"ho_id,omitempty"`
	HoName string `json:"ho_name,omitempty"`
	HroId int32 `json:"hro_id,omitempty"`
	HroName string `json:"hro_name,omitempty"`
	Landmark string `json:"landmark,omitempty"`
	Latitude float32 `json:"latitude"`
	Longitude float32 `json:"longitude"`
	ModifiedFlag bool `json:"modified_flag,omitempty"`
	OfficeAddress1 string `json:"office_address1"`
	OfficeAddress2 string `json:"office_address2,omitempty"`
	OfficeAddress3 string `json:"office_address3,omitempty"`
	OfficeClass string `json:"office_class,omitempty"`
	OfficeLevel string `json:"office_level,omitempty"`
	OfficeName string `json:"office_name"`
	OfficeStreet string `json:"office_street,omitempty"`
	OfficeTypeCode string `json:"office_type_code"`
	OfficeTypeId int32 `json:"office_type_id"`
	OrderMemoNumber string `json:"order_memo_number,omitempty"`
	PaoCode string `json:"pao_code,omitempty"`
	Pincode int32 `json:"pincode"`
	PliId string `json:"pli_id,omitempty"`
	QrTerminalId string `json:"qr_terminal_id,omitempty"`
	RegionName string `json:"region_name,omitempty"`
	RegionOfficeId int32 `json:"region_office_id,omitempty"`
	Remarks string `json:"remarks,omitempty"`
	ReportingOfficeId int32 `json:"reporting_office_id,omitempty"`
	SoId int32 `json:"so_id,omitempty"`
	SoName string `json:"so_name,omitempty"`
	SolId string `json:"sol_id,omitempty"`
	SroId int32 `json:"sro_id,omitempty"`
	SroName string `json:"sro_name,omitempty"`
	StateName string `json:"state_name"`
	SubdivisionName string `json:"subdivision_name,omitempty"`
	SubdivisionOfficeId int32 `json:"subdivision_office_id,omitempty"`
	SupportedDocumentPath string `json:"supported_document_path,omitempty"`
	TalukName string `json:"taluk_name,omitempty"`
	UpdatedBy string `json:"updated_by,omitempty"`
	ValidFrom string `json:"valid_from"`
	ValidTo string `json:"valid_to"`
	VillageName string `json:"village_name,omitempty"`
	WegCode string `json:"weg_code,omitempty"`
	WorkingDays string `json:"working_days"`
	WorkingHoursFrom string `json:"working_hours_from"`
	WorkingHoursTo string `json:"working_hours_to"`
}
