/*
 * Master Data Management API
 *
 * A comprehensive API suite for managing various aspects of the postal system, including office management, product management, tariffs (domestic and international), product country mapping, local pin codes, country details, and currency exchange rates. Additionally, the API supports insurance quote generation for PLI/RPLI, and interest rate calculations for savings schemes such as SB, SSA, PPF, MIS, TD, NSC/KVP, SCSS, and MSS.
 *
 * API version: 1.0
 * Contact: support_cept@indiapost.gov.in
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ResponseGetScssIntBaseResponse struct {
	NetAmount float32 `json:"net_amount,omitempty"`
	NetInterest float32 `json:"net_interest,omitempty"`
	NetPayableInterest float32 `json:"net_payable_interest,omitempty"`
	QuarterlyInterest float32 `json:"quarterly_interest,omitempty"`
	Tds float32 `json:"tds,omitempty"`
	Year int32 `json:"year,omitempty"`
}
