/*
 * Postman Delivery Management
 *
 * This is Postman Delivery Management API with Swagger documentation
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type HandlerCreateSortingSequencingsRequest struct {
	ArticleNumber string `json:"article_number,omitempty"`
	ArticleReceivedDate string `json:"article_received_date,omitempty"`
	ArticleType string `json:"article_type,omitempty"`
	ArticleWeight float32 `json:"article_weight,omitempty"`
	BagId string `json:"bag_id,omitempty"`
	BatchName string `json:"batch_name,omitempty"`
	BeatName string `json:"beat_name,omitempty"`
	BookingDate string `json:"booking_date,omitempty"`
	CodValue float32 `json:"cod_value,omitempty"`
	CreatedBy string `json:"created_by,omitempty"`
	CustomsDuty float32 `json:"customs_duty,omitempty"`
	DeliveryInstruction string `json:"delivery_instruction,omitempty"`
	DestinationOfficeId int32 `json:"destination_office_id,omitempty"`
	DestinationOfficeName string `json:"destination_office_name,omitempty"`
	DestinationPincode int32 `json:"destination_pincode,omitempty"`
	InsuredValue float32 `json:"insured_value,omitempty"`
	IsCod bool `json:"is_cod,omitempty"`
	IsInsured bool `json:"is_insured,omitempty"`
	IsInvoiced bool `json:"is_invoiced,omitempty"`
	IsSpds bool `json:"is_spds,omitempty"`
	IsTakenForInvoice bool `json:"is_taken_for_invoice,omitempty"`
	IsVpp bool `json:"is_vpp,omitempty"`
	ReceivedAtOfficeId int32 `json:"received_at_office_id,omitempty"`
	ReceivedAtOfficeName string `json:"received_at_office_name,omitempty"`
	ReceivedOfficePincode int32 `json:"received_office_pincode,omitempty"`
	ReceiverAddress1 string `json:"receiver_address1,omitempty"`
	ReceiverAddress2 string `json:"receiver_address2,omitempty"`
	ReceiverAddress3 string `json:"receiver_address3,omitempty"`
	ReceiverAdharno int32 `json:"receiver_adharno,omitempty"`
	ReceiverCity string `json:"receiver_city,omitempty"`
	ReceiverMobileno int32 `json:"receiver_mobileno,omitempty"`
	ReceiverName string `json:"receiver_name,omitempty"`
	ReceiverPincode int32 `json:"receiver_pincode,omitempty"`
	ReceiverState string `json:"receiver_state,omitempty"`
	SenderAddress1 string `json:"sender_address1,omitempty"`
	SenderAddress2 string `json:"sender_address2,omitempty"`
	SenderAddress3 string `json:"sender_address3,omitempty"`
	SenderAlternateAddress1 string `json:"sender_alternate_address1,omitempty"`
	SenderAlternateAddress2 string `json:"sender_alternate_address2,omitempty"`
	SenderAlternateAddress3 string `json:"sender_alternate_address3,omitempty"`
	SenderAlternateCity string `json:"sender_alternate_city,omitempty"`
	SenderAlternateMobileno int32 `json:"sender_alternate_mobileno,omitempty"`
	SenderAlternatePincode int32 `json:"sender_alternate_pincode,omitempty"`
	SenderAlternateState string `json:"sender_alternate_state,omitempty"`
	SenderCity string `json:"sender_city,omitempty"`
	SenderMobileno int32 `json:"sender_mobileno,omitempty"`
	SenderName string `json:"sender_name,omitempty"`
	SenderPincode int32 `json:"sender_pincode,omitempty"`
	SenderState string `json:"sender_state,omitempty"`
	Sequencenumber string `json:"sequencenumber,omitempty"`
	SourceOfficeId int32 `json:"source_office_id,omitempty"`
	SourceOfficeName string `json:"source_office_name,omitempty"`
	SourcePincode int32 `json:"source_pincode,omitempty"`
	TotalTariff float32 `json:"total_tariff,omitempty"`
	VppCommission float32 `json:"vpp_commission,omitempty"`
	VppValue float32 `json:"vpp_value,omitempty"`
}
