/*
 * Master Data Management API
 *
 * A comprehensive API suite for managing various aspects of the postal system, including office management, product management, tariffs (domestic and international), product country mapping, local pin codes, country details, and currency exchange rates. Additionally, the API supports insurance quote generation for PLI/RPLI, and interest rate calculations for savings schemes such as SB, SSA, PPF, MIS, TD, NSC/KVP, SCSS, and MSS.
 *
 * API version: 1.0
 * Contact: support_cept@indiapost.gov.in
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type HandlerUpdateCountryRequest struct {
	AirMailSurchargeIndicatorFlag bool `json:"air_mail_surcharge_indicator_flag"`
	AmsApplicableCharge int32 `json:"ams_applicable_charge"`
	ContinentCode string `json:"continent_code,omitempty"`
	ContinentName string `json:"continent_name,omitempty"`
	CountryCode string `json:"country_code"`
	CountryIsdCode string `json:"country_isd_code,omitempty"`
	CountryName string `json:"country_name"`
	SalApplicableCharge float32 `json:"sal_applicable_charge"`
	Status string `json:"status"`
	SurfaceAirLiftedIndicator bool `json:"surface_air_lifted_indicator"`
	UpdatedBy string `json:"updated_by"`
}
