/*
 * Postman Delivery Management
 *
 * This is Postman Delivery Management API with Swagger documentation
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type DomainSubmitAccount struct {
	Pincode int32 `json:"Pincode,omitempty"`
	Articlecount int32 `json:"articlecount,omitempty"`
	Batchname string `json:"batchname,omitempty"`
	Beatname string `json:"beatname,omitempty"`
	Createdat string `json:"createdat,omitempty"`
	Createdby string `json:"createdby,omitempty"`
	Date string `json:"date,omitempty"`
	Emocount int32 `json:"emocount,omitempty"`
	Officeid int32 `json:"officeid,omitempty"`
	Postagedue float32 `json:"postagedue,omitempty"`
	Requestid string `json:"requestid,omitempty"`
	Requserid int32 `json:"requserid,omitempty"`
	Submitaccount bool `json:"submitaccount,omitempty"`
	Submitaccountid int32 `json:"submitaccountid,omitempty"`
	Totalamount float32 `json:"totalamount,omitempty"`
}
