/*
 * Postman Delivery Management
 *
 * This is Postman Delivery Management API with Swagger documentation
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type HandlerCreateEmoReturnsBulkSupervisorApprovalRequest struct {
	BeatName string `json:"beat_name"`
	CurrentUser string `json:"current_user"`
	EmoRemarksIdArray []HandlerEmoRemarksId `json:"emo_remarks_id_array"`
	OfficeId int32 `json:"office_id"`
}
