/*
 * Postman Delivery Management
 *
 * This is Postman Delivery Management API with Swagger documentation
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// MetaDataResponse     `json:\",inline\"` // Add metadata if needed
type ResponseAmountStatisticsDashboardApiResponseData struct {
}
