/*
 * Postman Delivery Management
 *
 * This is Postman Delivery Management API with Swagger documentation
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ResponseListEmOsSupervisorApprovalResponse struct {
	ActionCode int32 `json:"action_code,omitempty"`
	ActionToBeTaken string `json:"action_to_be_taken,omitempty"`
	BookingDate string `json:"booking_date,omitempty"`
	CurrentOfficeId int32 `json:"current_office_id,omitempty"`
	CurrentOfficeName string `json:"current_office_name,omitempty"`
	DestinationOfficeId int32 `json:"destination_office_id,omitempty"`
	DestinationOfficeName string `json:"destination_office_name,omitempty"`
	DestinationPincode int32 `json:"destination_pincode,omitempty"`
	EmoMessage string `json:"emo_message,omitempty"`
	EmoNumber string `json:"emo_number,omitempty"`
	EmoValue float32 `json:"emo_value,omitempty"`
	IsInvoiced bool `json:"is_invoiced,omitempty"`
	IsPrinted bool `json:"is_printed,omitempty"`
	ReceiverAddress1 string `json:"receiver_address1,omitempty"`
	ReceiverAddress2 string `json:"receiver_address2,omitempty"`
	ReceiverAddress3 string `json:"receiver_address3,omitempty"`
	ReceiverCity string `json:"receiver_city,omitempty"`
	ReceiverMobileNo int32 `json:"receiver_mobile_no,omitempty"`
	ReceiverName string `json:"receiver_name,omitempty"`
	ReceiverState string `json:"receiver_state,omitempty"`
	Remarks string `json:"remarks,omitempty"`
	RemarksId string `json:"remarks_id,omitempty"`
	SenderAddress1 string `json:"sender_address1,omitempty"`
	SenderAddress2 string `json:"sender_address2,omitempty"`
	SenderAddress3 string `json:"sender_address3,omitempty"`
	SenderAlternateAddress1 string `json:"sender_alternate_address1,omitempty"`
	SenderAlternateAddress2 string `json:"sender_alternate_address2,omitempty"`
	SenderAlternateAddress3 string `json:"sender_alternate_address3,omitempty"`
	SenderAlternateCity string `json:"sender_alternate_city,omitempty"`
	SenderAlternateMobileNo int32 `json:"sender_alternate_mobile_no,omitempty"`
	SenderAlternatePincode int32 `json:"sender_alternate_pincode,omitempty"`
	SenderAlternateState string `json:"sender_alternate_state,omitempty"`
	SenderCity string `json:"sender_city,omitempty"`
	SenderMobileNo int32 `json:"sender_mobile_no,omitempty"`
	SenderName string `json:"sender_name,omitempty"`
	SenderPincode int32 `json:"sender_pincode,omitempty"`
	SenderState string `json:"sender_state,omitempty"`
	SourceOfficeId int32 `json:"source_office_id,omitempty"`
	SourceOfficeName string `json:"source_office_name,omitempty"`
	SourcePincode int32 `json:"source_pincode,omitempty"`
}
