/*
 * Postman Delivery Management
 *
 * This is Postman Delivery Management API with Swagger documentation
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ResponseEpostResponse struct {
	Content string `json:"content,omitempty"`
	CreatedDate string `json:"created_date,omitempty"`
	EpostId int32 `json:"epost_id,omitempty"`
	IsPrinted bool `json:"is_printed,omitempty"`
	IsReceived bool `json:"is_received,omitempty"`
	MessageSubtype string `json:"message_subtype,omitempty"`
	MessageType string `json:"message_type,omitempty"`
	NoOfPages int32 `json:"no_of_pages,omitempty"`
	NoOfRecipients int32 `json:"no_of_recipients,omitempty"`
	OfficeIdBkg int32 `json:"office_id_bkg,omitempty"`
	ReceiverAddress string `json:"receiver_address,omitempty"`
	ReceiverDpo int32 `json:"receiver_dpo,omitempty"`
	ReceiverEmailid string `json:"receiver_emailid,omitempty"`
	ReceiverMobilenumber int32 `json:"receiver_mobilenumber,omitempty"`
	ReceiverName string `json:"receiver_name,omitempty"`
	ReceiverOfficeid int32 `json:"receiver_officeid,omitempty"`
	ReceiverPincode int32 `json:"receiver_pincode,omitempty"`
	ReceiverState string `json:"receiver_state,omitempty"`
	SenderAddress string `json:"sender_address,omitempty"`
	SenderDpo int32 `json:"sender_dpo,omitempty"`
	SenderEmailid string `json:"sender_emailid,omitempty"`
	SenderMobilenumber int32 `json:"sender_mobilenumber,omitempty"`
	SenderName string `json:"sender_name,omitempty"`
	SenderPincode int32 `json:"sender_pincode,omitempty"`
	SenderState string `json:"sender_state,omitempty"`
	StatusCd string `json:"status_cd,omitempty"`
	Subject string `json:"subject,omitempty"`
	TotalAmount float32 `json:"total_amount,omitempty"`
}
